sandbox_mode = "workspace-write"
approval_policy = "never"

[windows]
sandbox = "elevated"

[sandbox_workspace_write]
network_access = true
exclude_tmpdir_env_var = true
exclude_slash_tmp = true
writable_roots = []